### ISSUE TITLE
Incorrect mag data

### ISSUE THREAD

**Issue by Clovis5119** [Mitcheljager/apexdata#18]
The ammo increase from the extended mags is incorrect. The 25/50/100% increase is only accurate for three of the weapons in the game (Wingman, Longbow, and G7 Scout). None of the other weapons get quite that big of an ammo increase. For example the Flatline has 20/25/28/30 ammo, not 20/25/30/40.

**Comment by Mitcheljager** [comment]
This has been fixed with https://github.com/Mitcheljager/apexdata/commit/f551d5d31e8d60fd5fe53ea78ea884da9d86b711, thanks for reporting it!
