### ISSUE TITLE
Incorrect helmet datas

### ISSUE THREAD

**Issue by John-Loup** [Mitcheljager/apexdata#19]
**There is wrong datas on the helmet at** : https://www.apexdata.gg/equipment
_The correct datas are : 
Helmet
(Level 1)    Common
(White)    10% total Damage Reduction
Helmet
(Level 2)    Rare
(Blue)    20% total Damage Reduction
Helmet
(Level 3)    Epic
(Purple)    25% total Damage Reduction
Helmet
(Level 4)    Legendary
(Gold)    25% total Damage Reduction,
and increases charge speed of Tactical and Ultimate abilities._

It makes a difference when you equip hop-ups.
Example 1 : wingman + skullpiercer headshot on lvl 3 helmet = 45+(90-45) = 90 (50% headshot damages reduction)
Example 2 : wingman + skullpiercer headshot on lvl 3 helmet = (45+90)-33.75 = 101.25 (25% total damages reduction)

I have experienced this in-game, and the its definitely 25% total damages reduction.

**Comment by Mitcheljager** [comment]
You're right, thanks for noting down the values! This has been fixed with 7299ff8e105c6d75db70baf7c03db85c399c163c
