### ISSUE TITLE
Spray picture doesn't work on Firefox

### ISSUE THREAD

**Issue by yoanmalie** [Mitcheljager/apexdata#20]
For the example here for the Mozambique :
![image](https://user-images.githubusercontent.com/3357171/53962028-5ab75500-40ea-11e9-9fbc-fce2d10dc862.png)

Firefox 65.0.1
MacOS 10.14.3

**Comment by Mitcheljager** [comment]
Interesting! Turns out Firefox doesn't quite support the SVG 2 meaning `cx` and `cy` can't be used as CSS properties. In any case, this has with 2cbcba71c9ecbb8304debd8208ef002c239c0a98. Thanks for the report!
